name: checkout
description: "Supermarket checkout Kata"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  auto_route: ^8.0.3
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  get_it: ^7.6.8
  injectable: ^2.4.2
  flutter_bloc: ^8.1.6
  flutter:
    sdk: flutter
  meta: ^1.12.0

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  injectable_generator: ^2.6.1

flutter:
  uses-material-design: true
