name: checkout
description: "Supermarket checkout Kata"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  auto_route: ^10.1.2
  bloc: ^9.1.0
  cached_network_image: ^3.4.1
  collection: ^1.19.1
  decimal: ^3.2.4
  equatable: ^2.0.7
  get_it: ^8.2.0
  injectable: ^2.5.2
  flutter_bloc: ^9.1.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.1
  meta: ^1.16.0
  shimmer: ^3.0.0
  stream_transform: ^2.1.1

dev_dependencies:
  auto_route_generator: ^10.2.4
  build_runner: ^2.7.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  injectable_generator: ^2.8.1
  mockito: ^5.4.6
  test: ^1.26.2

flutter:
  uses-material-design: true
  assets:
    - assets/
